### ISSUE TITLE
Add reusable GHA workflow to allow for CI checks

### ISSUE THREAD

**Issue by internalsystemerror** [laminas/laminas-cache-storage-adapter-zend-server#11]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

In order to allow renovate to properly rely on CI, we need to add the reusable GHA workflow to this repository

**Comment by Ocramius** [comment]
Related: https://github.com/laminas/laminas-cache-storage-adapter-zend-server/issues/12
